name: Test local composite action

on: [ push, pull_request ]

jobs:
  test-composite:
    name: Test local composite on Python${{ matrix.python-version }} freethreaded ${{ matrix.freethreaded }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ windows-2019, windows-2022, windows-2025, windows-latest ]
        python-version: [ "3.9", "3.10", "3.11", "3.12", "3.13" ]
        freethreaded: [ false, true ]
        exclude:
          - python-version: "3.9"
            freethreaded: true
          - python-version: "3.10"
            freethreaded: true
          - python-version: "3.11"
            freethreaded: true
          - python-version: "3.12"
            freethreaded: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run local composite action
        uses: ./.github/actions/setup-python-win7
        with:
          python-version: ${{ matrix.python-version }}
          freethreaded: ${{ matrix.freethreaded }}
      - name: Check Python for Windows7
        shell: cmd
        run: |
          echo %PYTHON_WIN7_HOME%
          python -c "import sys; print(sys.version)"
